### ISSUE TITLE
Error when trying to import module

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician-python#2]
# Problem

I get the following error when I try to `import everypolitician`:

```
$ python
Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import everypolitician
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/everypolitician/__init__.py", line 1, in <module>
    from .lib import *
  File "/usr/local/lib/python2.7/site-packages/everypolitician/lib.py", line 21, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

Which appears to be a problem with `six`.

```
$ pip freeze | grep six
six==1.8.0
```

I've got version 1.8.0, it looks like `python_2_unicode_compatible` was only [added in 1.9.0](https://bitbucket.org/gutworth/six/src/ca4580a5a648fc75abc568907e81abc80b05d58c/CHANGES?at=default&fileviewer=file-view-default#CHANGES-29:35).
# Proposed solution

Make the version of `six` that we depend on more explicit in `setup.py`.

**Comment by mhl** [comment]
Thanks, @chrismytton - I'd been testing this in new virtualenvs, where there would have been no previous version of six installed. I've updated the dependency.
